---

- name: Update profile timezone
  become: yes
  lineinfile:
    dest: ~/.profile
    state: present
    line: "TZ='America/New_York'; export TZ"

- name: Install packages
  become: yes
  vars:
    packages:
      - vim
      - motion
      - nodejs
      - npm
  apt:
    name: "{{ packages }}"
    update_cache: yes

- name: Copy pollofeed app files
  tags: copy_files
  with_items:
    - pollofeed.py
    - pin.py
    - setup.py
    - config.yml
    - ngrok.yml
    - requirements.txt
  copy:
    src: "{{ item }}"
    dest: "{{ pollofeed_dir }}/{{ item }}"

- name: Copy motion.conf
  tags: copy_motion_conf
  become: yes
  copy:
    src: motion.conf
    dest: /etc/motion/motion.conf



- name: Install python requirements
  tags: install_requirements
  pip:
    requirements: "{{ pollofeed_dir }}/requirements.txt"


### NPM GLOBAL PACKAGES

- name: Update npm global version 6.9.0
  become: yes
  tags: npm_1
  npm:
    global: yes
    name: npm
    version: "6.9.0"



- name: Install ngrok globally
  become: yes
  tags: install_ngrok
  npm:
    global: yes
    name: ngrok
    unsafe_perm: yes



- name: cron motion
  tags: motion_reboot
  become: yes
  cron:
    state: absent
    name: motion_reboot
    special_time: reboot
    job: "sudo motion -c /etc/motion/motion.conf"

### SERVICES

- name: Set variable - services
  tags: set_facts
  set_fact:
    services:
      - ngrok
      - pollofeed
      - motion

- name: Copy service files
  become: yes
  tags: copy_services
  with_items: "{{ services }}"
  copy:
    src: "{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"


- name: Enable and start services
  with_items: "{{services}}"
  tags: enable_services
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started

- name: reload systemd
  tags: reload_systemd
  systemd:
    daemon_reload: yes
